# Generated by Django 4.2.1 on 2023-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="image/no-image.svg",
                upload_to="profile_image",
            ),
        ),
    ]
