# Generated by Django 4.2.1 on 2023-06-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_registration", "0002_alter_userinfo_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="image/no-image.svg", upload_to="profile_image"
            ),
        ),
    ]
